<?php
if ( ! defined( 'ABSPATH' ) ) exit;

esc_html_e( 'Credit', 'malga-payments-gateway' );
esc_html_e( 'Invalid CVV', 'malga-payments-gateway' );
esc_html_e( 'Enable Credit', 'malga-payments-gateway' );
esc_html_e( 'Enable Pix', 'malga-payments-gateway' );
esc_html_e( 'Enable Boleto', 'malga-payments-gateway' );
esc_html_e( 'credit discount', 'malga-payments-gateway' );
esc_html_e( 'pix discount', 'malga-payments-gateway' );
esc_html_e( 'boleto discount', 'malga-payments-gateway' );
esc_html_e( 'invalid_cvv', 'malga-payments-gateway' );
esc_html_e( 'merchant_not_found', 'malga-payments-gateway' );
esc_html_e( 'payment_not_supported', 'malga-payments-gateway' );
esc_html_e( 'provider_not_found', 'malga-payments-gateway' );
esc_html_e( 'invalid_document', 'malga-payments-gateway' );
esc_html_e( 'unauthorized_adapter', 'malga-payments-gateway' );
esc_html_e( 'card_pending_validation', 'malga-payments-gateway' ); 
esc_html_e( 'card_not_found', 'malga-payments-gateway' );
esc_html_e( 'invalid_source_type', 'malga-payments-gateway' );
esc_html_e( 'invalid_card_number', 'malga-payments-gateway' );
esc_html_e( 'invalid_holder_name', 'malga-payments-gateway' );
esc_html_e( 'invalid_expiration_date', 'malga-payments-gateway' );
esc_html_e( 'invalid_card_cvv', 'malga-payments-gateway' );
esc_html_e( 'customer_not_found', 'malga-payments-gateway' );
esc_html_e( 'customer_has_not_pre_authorized', 'malga-payments-gateway' );
esc_html_e( 'amount_cannot_be_greater_than_transaction', 'malga-payments-gateway' );
esc_html_e( 'refund_greater_than_transaction', 'malga-payments-gateway' );
esc_html_e( 'charge_has_not_yet_canceled', 'malga-payments-gateway' );
esc_html_e( 'charge_already_voided', 'malga-payments-gateway' );
esc_html_e( 'transaction_not_found', 'malga-payments-gateway' );
esc_html_e( 'transaction_has_not_pre_authorized', 'malga-payments-gateway' );
